version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  run_tests:
    executor: node/default

    steps:
      - checkout

      - run:
          name: install required packages
          command: npm install mocha supertest chai chai-http

      - run:
          name: Run tests
          command: npm test
      - run:
          name: Exit with code 0 if tests pass
          command: |
            if [ "${CIRCLE_TEST_REPORTS}" != "" ]; then
               exit 0
            else
               exit 1
            fi


             

workflows:
  build-and-test:
    jobs:
      - run_tests
