version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: node:14.15

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            npm install
      - run: npm install mocha
      - run: npm i -D nyc

      - run:
          name: Run Tests
          command: |
            npm run test-with-coverage
      - run:
          name: Exit
          command: |
            ctrl + c
     
workflows:
  testing:
    jobs:
      - build


