version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      - run: npm install
      - run: npm install mocha
      - run: npm install chai
      - run: npm install chai-http

      - run:
          name: "start testing"
          command: npm test

