version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  run_tests:
    executor: node/default

    steps:
      - checkout

      - run:
          name: install required packages
          command: npm install mocha supertest chai chai-http

      - run:
          name: Run tests
          command: npm test         

workflows:
  build-and-test:
    jobs:
      - run_tests
