version: 2.1

jobs:
  build:
    docker:
      - image: node:14

    working_directory: ~/app

    steps:
      - checkout

      - run:
          name: install mocha 
          command: npm install mocha

      - run:
          name: Run tests
          command: npm test

      - run:
          name: Connect to MongoDB Compass
          command: |
            echo "Connecting to MongoDB Compass..."
            mongodb-compass-cli connect \
              --host=127.0.0.1 \
              --port=27017 \
             

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
