version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:10

    steps:
      - checkout

      - run:
          name: install required packages
          command: npm install mocha supertest chai chai-http

      - run:
          name: Run tests
          command: npm test

             

workflows:
  build-and-test:
    jobs:
      - run_tests
