version: 2.1 
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ epoch }}
      - run: npm install
      - run: npm install mocha chai chai-http
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ epoch }}
          paths:
            - node_modules
     connection:
          host: 127.0.0.1
          port: 27017

      - run:
          name: "Run Mocha tests"
          command: npm test


